tesina:
  titolo: "Live Electronics: un racconto plurale. Oltre i confini di una storiografia eurocentrica."
  sottotitolo: "Tecnologia, contesti istituzionali e trasformazione il pensiero musicale e della prassi nel Live Electronics: Le storie "
  autore: "Giulio Romano De Mattia" 
  
  # Dati per il conservatorio
  conservatorio: "Conservatorio A. Casella"
  citta: "L'Aquila"
  corso: "Musica Elettronica DCSL34"

  # Dati specifici dell'esame
  esame: "Storia della musica elettrocustica e Storia delle tecnologie elettroacustiche"
  data: "15/03/2026"

  
environment:
  font: #arial
